services:
  web:
    build: .
    container_name: devopsapp_web
    env_file:
      - .env
    volumes:
      - ./db/data:/app/db/data
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: devopsapp_nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
